import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import '../../app/theme/app_colors.dart';
import '../../app/theme/app_spacing.dart';
import '../../app/theme/app_typography.dart';
import '../../core/widgets/primary_button.dart';
import '../../providers/goal_provider.dart';

class GoalInputScreen extends ConsumerStatefulWidget { const GoalInputScreen({super.key}); @override ConsumerState<GoalInputScreen> createState()=>_GoalInputState(); }
class _GoalInputState extends ConsumerState<GoalInputScreen>{late final TextEditingController c; @override void initState(){super.initState();c=TextEditingController();} @override void dispose(){c.dispose();super.dispose();} Future<void> submit() async {ref.read(goalProvider.notifier).setInput(c.text); final ok=await ref.read(goalProvider.notifier).createPlan(); if(!mounted)return; if(ok){context.push('/plan');}else{final e=ref.read(goalProvider).error; ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(e??'Unable to create a plan')));}} void demo(){const x='I have ₦300,000 available. Help me move ₦100,000 to my bank so it\'s safely set aside.';c.text=x;ref.read(goalProvider.notifier).setInput(x);setState((){});} @override Widget build(BuildContext context){return SafeArea(child:ListView(padding:const EdgeInsets.fromLTRB(20,18,20,30),children:[Row(children:[IconButton(onPressed:()=>context.canPop()?context.pop():context.go('/home'),icon:const Icon(Icons.arrow_back)),const SizedBox(width:4),const Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('FlowPilot',style:AppTypography.title),Text('AI Financial Copilot',style:AppTypography.muted)])]),const SizedBox(height:28),Container(padding:const EdgeInsets.all(18),decoration:BoxDecoration(color:AppColors.surface,borderRadius:BorderRadius.circular(16),border:Border.all(color:AppColors.border)),child:const Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Tell me what you want to do with your money.',style:TextStyle(fontSize:18,fontWeight:FontWeight.w600)),SizedBox(height:8),Text('I’ll turn it into a clear action plan for you to review. Nothing is executed automatically.',style:AppTypography.muted)])),const SizedBox(height:22),const Text('What would you like to accomplish?',style:AppTypography.section),const SizedBox(height:10),TextField(controller:c,minLines:6,maxLines:9,onChanged:(v)=>ref.read(goalProvider.notifier).setInput(v),textInputAction:TextInputAction.newline,decoration:const InputDecoration(hintText:'e.g. Move ₦100,000 to my bank account',alignLabelWithHint:true)),const SizedBox(height:16),const Text('Try the demo',style:AppTypography.muted),const SizedBox(height:8),GestureDetector(onTap:demo,child:Container(padding:const EdgeInsets.all(13),decoration:BoxDecoration(color:AppColors.elevated,borderRadius:BorderRadius.circular(12),border:Border.all(color:AppColors.border)),child:const Row(children:[Icon(Icons.auto_awesome,size:17,color:AppColors.accent),SizedBox(width:9),Expanded(child:Text('“I have ₦300,000 available. Help me move ₦100,000 to my bank so it’s safely set aside.”',style:TextStyle(fontSize:13,height:1.4))),Icon(Icons.add,size:18,color:AppColors.secondaryText)]))),const SizedBox(height:24),PrimaryButton(label:'Create Plan',onPressed:submit)]));}}
